name: Auto publish canary

on:
  pull_request:
    # 只监听标签添加事件
    types: [labeled]

# 设置环境变量
env:
  CI: true
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  canary:
    # 检查标签名称
    if: github.event.label.name == 'release:snapshot'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Global install Pnpm 🔨
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.0

      - name: Print Env 📄
        run: |
          echo "node"
          node -v
          echo "npm"
          npm -v
          echo "pnpm"
          pnpm -v

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v5
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile

      - name: Config npm
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Snapshot
        run: pnpm run release:snapshot
