name: 'TESTS CI'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# 设置环境变量
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  test-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: Global install Pnpm 🔨
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile

      - name: Run test
        run: pnpm run test:coverage

      - name: upload coverage report to codeCov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }} # required
